# 1. Установка и импорт библиотеки

In [15]:
import numpy as np

print(f"Установленная версия NumPy: {np.__version__}")

Установленная версия NumPy: 2.3.3


# 2. Создание массивов
Рассмотрим создание массива из обычного списка Python, а также встроенные генераторы массивов (zeros, ones, arange, linspace) из NumPy.

In [16]:
# Создание массива из простого списка Python
py_list = [1, 2, 3, 4, 5]
arr_from_list = np.array(py_list)

# Массив из нулей (например, матрица 3x3)
zeros_arr = np.zeros((3, 3))

# Массив из единиц
ones_arr = np.ones((2, 4))

# Диапазон чисел (от 0 до 10 с шагом 2)
range_arr = np.arange(0, 10, 2)

# Равномерное распределение (5 чисел от 0 до 1)
linspace_arr = np.linspace(0, 1, 5)

# Случайные числа (матрица 2x3 со значениями от 0 до 1)
random_arr = np.random.rand(2, 3)

print("Из списка:", arr_from_list)
print("\nНули:\n", zeros_arr)
print("\nRange:", range_arr)
print("\nСлучайный массив:\n", random_arr)

Из списка: [1 2 3 4 5]

Нули:
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

Range: [0 2 4 6 8]

Случайный массив:
 [[0.76702823 0.93517447 0.06470595]
 [0.12909385 0.58220051 0.19583198]]


# 3. Shape (форма) и dtype (тип данных)

In [17]:
# Создадим массив для тестов
data = np.array([[1, 2, 3], [4, 5, 6]])

print("Массив:\n", data)
print("Размерность (ndim):", data.ndim)       # Размерность массива (2)
print("Форма (shape):", data.shape)           # Форма (2 строки, 3 столбца)
print("Всего элементов (size):", data.size)   # 2 * 3 = 6
print("Тип данных (dtype):", data.dtype)      # Например, int64 или int32

# Изменение типа данных (приведение к типу)
float_data = data.astype(np.float64)
print("\nМассив как float:\n", float_data)

Массив:
 [[1 2 3]
 [4 5 6]]
Размерность (ndim): 2
Форма (shape): (2, 3)
Всего элементов (size): 6
Тип данных (dtype): int64

Массив как float:
 [[1. 2. 3.]
 [4. 5. 6.]]


# 4. Индексирование и срезы (Slicing)
Похоже на обычные списки из Python, но можно работать с многомерными данными через запятую [row, col].

In [18]:
matrix = np.array([[10, 20, 30],
                   [40, 50, 60],
                   [70, 80, 90]])

# Получение конкретного элемента [строка, столбец]
element = matrix[1, 2]  # вторая строка (индекс 1), третий столбец (индекс 2) -> 60

# Срез: берем первые две строки и столбцы с первого до конца
slice_example = matrix[:2, 1:]

# Изменение значения через срез
matrix[0, 0] = 999

print("Элемент [1, 2]:", element)
print("Срез [:2, 1:]:\n", slice_example)
print("Измененная матрица:\n", matrix)

Элемент [1, 2]: 60
Срез [:2, 1:]:
 [[20 30]
 [50 60]]
Измененная матрица:
 [[999  20  30]
 [ 40  50  60]
 [ 70  80  90]]


# 5. Простые операции

In [19]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Поэлементные операции
sum_ab = a + b      # [5 7 9]
mult_ab = a * b     # [4 10 18]
pow_a = a ** 2      # [1 4 9]

# Матричное умножение (скалярное произведение)
# Для одномерных массивов это скалярное произведение, для двумерных - матричное
dot_product = np.dot(a, b) # 1*4 + 2*5 + 3*6 = 32

print("Сумма:", sum_ab)
print("Умножение:", mult_ab)
print("Квадрат a:", pow_a)
print("Скалярное произведение:", dot_product)

# Матричные операции
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Транспонирование:", matrix.T)
print("Умножение матриц:")
print(np.dot(matrix, matrix))

# Логические операции
print("\nЛогические операции:")
print("a > 2 =", a > 2) # Возвращает все элементы больше чем 2
print("a == b =", a == b) # Возвращает, какие элементы совпали (в данном случае они не должны совпадать)
print("Элементы a больше 1:", a[a > 1])

Сумма: [5 7 9]
Умножение: [ 4 10 18]
Квадрат a: [1 4 9]
Скалярное произведение: 32
Транспонирование: [[1 4 7]
 [2 5 8]
 [3 6 9]]
Умножение матриц:
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]

Логические операции:
a > 2 = [False False  True]
a == b = [False False False]
Элементы a больше 1: [2 3]


# 6. Статистики

In [20]:
stats_data = np.array([[1, 2, 3],
                       [4, 5, 6]])

total_sum = stats_data.sum()
mean_val = stats_data.mean()
max_in_cols = stats_data.max(axis=0) # Максимум в каждом столбце
sum_rows = stats_data.sum(axis=1)    # Сумма каждой строки

print(f"Общая сумма: {total_sum}")
print(f"Среднее: {mean_val}")
print(f"Максимумы по столбцам: {max_in_cols}") # [4 5 6]
print(f"Суммы по строкам: {sum_rows}")         # [6 15]

Общая сумма: 21
Среднее: 3.5
Максимумы по столбцам: [4 5 6]
Суммы по строкам: [ 6 15]


# 7. Дополнительные примеры
Например, Reshape часто используется для подготовки данных, а маски - для их фильтрации.

In [21]:
# 1. Reshape: превратим массив из 12 элементов в матрицу 4x3
flat_arr = np.arange(12)
reshaped_arr = flat_arr.reshape(4, 3)

print("Reshaped (4x3):\n", reshaped_arr)

# 2. Логическая маска
# Найдём все элементы больше 5
mask = flat_arr > 5
filtered_data = flat_arr[mask]

print("\nМаска (где > 5):", mask)
print("Отфильтрованные данные:", filtered_data)

# 3. np.where (аналог if для каждого элемента)
# Если элемент > 5, заменим на 1, иначе на -1
binary_arr = np.where(flat_arr > 5, 1, -1)
print("\nЗамена по условию (np.where):\n", binary_arr)

Reshaped (4x3):
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]

Маска (где > 5): [False False False False False False  True  True  True  True  True  True]
Отфильтрованные данные: [ 6  7  8  9 10 11]

Замена по условию (np.where):
 [-1 -1 -1 -1 -1 -1  1  1  1  1  1  1]
